let btn1 = document.getElementById('btn1');
let btn2 = document.getElementById('btn2');
let btn3 = document.getElementById('btn3');
let planetimg = document.getElementById('planetimg');
let info = document.getElementById('information');

btn1.addEventListener("click",()=>{
    planetimg.src = "planet-earth.svg";
    info.innerHTML = "Earth is the third planet from the Sun in our solar system and is the only known celestial body to support life. It is often referred to as the 'Blue Planet' due to its abundant water, which covers about 71% of its surface.Life on Earth is concentrated in a relatively thin layer at and near the surface, where conditions are suitable for living organisms. Earth has one natural satellite, the Moon, which has a significant influence on Earth's tides and has been a subject of scientific exploration and cultural significance throughout human history"
})

btn2.addEventListener("click",()=>{
    planetimg.src = "planet-earth-internal.svg";
    info.innerHTML = "The Earth's crust is divided into large plates that are in constant motion. This movement leads to processes like earthquakes, volcanic eruptions, and the creation of mountains.Earth has a magnetic field that protects the planet from harmful solar radiation and cosmic particles. This magnetic field is generated by the movement of molten iron in the planet's outer core."
})

btn3.addEventListener("click", ()=>{
    planetimg.src = "planet-earth-internal.svg";
    info.innerHTML = "Earth has a diameter of approximately 12,742 kilometers (7,918 miles), making it the fifth-largest planet in our solar system.Its mass is about 5.97 x 10^24 kilograms, making it relatively dense compared to other planets.Earth has a vast amount of water, primarily stored in its oceans. The major oceans are the Pacific, Atlantic, Indian, Southern (Antarctic), and Arctic oceans"
})